### ISSUE TITLE
新版mosdns的需要的geodata和你的patch/wall/v2ray-geodata的来源/安装位置有冲突导致重复安装

### ISSUE THREAD

**Issue by Pacio** [xiangfeidexiaohuo/extra-ipk#7]
结果是路由器rom存了两份geodata, 大大占用了rom空间
一个安装在/rom/usr/share/v2ray/
一个安装在/usr/share/v2ray/

**Comment by xiangfeidexiaohuo** [comment]
> 结果是路由器rom存了两份geodata, 大大占用了rom空间 一个安装在/rom/usr/share/v2ray/ 一个安装在/usr/share/v2ray/

没太注意，wall下面那个 从passwall 那边拉过来的

**Comment by Pacio** [comment]
> > 结果是路由器rom存了两份geodata, 大大占用了rom空间 一个安装在/rom/usr/share/v2ray/ 一个安装在/usr/share/v2ray/
> 
> 没太注意，wall下面那个 从passwall 那边拉过来的

好像只是镜像复制，删除其中一份geodata，rom空间并没有增加
