### ISSUE TITLE
homebox无法启动

### ISSUE THREAD

**Issue by pretendtobefree** [xiangfeidexiaohuo/extra-ipk#8]
编译正常通过，但homebox无法启动，错误提示如下：
/usr/lib/lua/luci/dispatcher.lua:477: Failed to execute cbi dispatcher target for entry '/admin/services/homebox'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'.
A runtime error occured: /usr/lib/lua/luci/template.lua:74: Failed to load template 'homebox_status'.
Error while parsing template '/usr/lib/lua/luci/view/homebox_status.htm':
Syntax error in /usr/lib/lua/luci/view/homebox_status.htm:1: unfinished string near '"
望指教，谢谢！

**Comment by xiangfeidexiaohuo** [comment]
> 编译正常通过，但homebox无法启动，错误提示如下： /usr/lib/lua/luci/dispatcher.lua:477: Failed to execute cbi dispatcher target for entry '/admin/services/homebox'. The called action terminated with an exception: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'. A runtime error occured: /usr/lib/lua/luci/template.lua:74: Failed to load template 'homebox_status'. Error while parsing template '/usr/lib/lua/luci/view/homebox_status.htm': Syntax error in /usr/lib/lua/luci/view/homebox_status.htm:1: unfinished string near '" 望指教，谢谢！

不懂你这个 我这一般都在大雕的LEDE上 是没问题的，其他openwrt 不清楚，也许兼容性不好。
