### ISSUE TITLE
luci-app-adguardhome端口显示修复

### ISSUE THREAD

**Issue by ghost** [xiangfeidexiaohuo/extra-ipk#9]
luci-app-adguardhome/luasrc/model/cbi/AdGuardHome/base.lua

local port=luci.sys.exec("awk '/  port:/{printf($2);exit;}' "..configpath.." 2>nul")

替换成
local port=luci.sys.exec("awk '/^dns:/ {found_dns=1} found_dns && /^  port:/ {print $2; exit}' "..configpath.." 2>nul")

![image](https://github.com/user-attachments/assets/d0db0799-0f66-4333-9fe2-a51e85369882)

**Comment by xiangfeidexiaohuo** [comment]
改一下 就可以是吧

**Comment by xiangfeidexiaohuo** [comment]
> luci-app-adguardhome/luasrc/model/cbi/AdGuardHome/base.lua
> 
> local port=luci.sys.exec("awk '/ port:/{printf($2);exit;}' "..configpath.." 2>nul")
> 
> 替换成 local port=luci.sys.exec("awk '/^dns:/ {found_dns=1} found_dns && /^ port:/ {print $2; exit}' "..configpath.." 2>nul")
> 
> ![image](https://private-user-images.githubusercontent.com/53441247/393706926-d0db0799-0f66-4333-9fe2-a51e85369882.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTU1MjUsIm5iZiI6MTczMzg5NTIyNSwicGF0aCI6Ii81MzQ0MTI0Ny8zOTM3MDY5MjYtZDBkYjA3OTktMGY2Ni00MzMzLTlmZTItYTUxZTg1MzY5ODgyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwNTMzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGY2MjU0MjY3YTJkZDZlNjZkNTk5ZWE5MjNkMDA3Y2Y2NWYzNTc1MmY1OGNkOTljNDk0Y2IzZjI0NWNlMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WPHIqLl7VbrdBDk5w7cFy8nNgl0MDbHUNVVd7MI3I_Q)

你这编码有问题吧，搞成代码格式 看看

**Comment by ghost** [comment]
> > luci-app-adguardhome/luasrc/model/cbi/AdGuardHome/base.lua
> 
> > 
> 
> > local port=luci.sys.exec("awk '/ port:/{printf($2);exit;}' "..configpath.." 2>nul")
> 
> > 
> 
> > 替换成 local port=luci.sys.exec("awk '/^dns:/ {found_dns=1} found_dns && /^ port:/ {print $2; exit}' "..configpath.." 2>nul")
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/53441247/393706926-d0db0799-0f66-4333-9fe2-a51e85369882.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4OTU1MjUsIm5iZiI6MTczMzg5NTIyNSwicGF0aCI6Ii81MzQ0MTI0Ny8zOTM3MDY5MjYtZDBkYjA3OTktMGY2Ni00MzMzLTlmZTItYTUxZTg1MzY5ODgyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwNTMzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGY2MjU0MjY3YTJkZDZlNjZkNTk5ZWE5MjNkMDA3Y2Y2NWYzNTc1MmY1OGNkOTljNDk0Y2IzZjI0NWNlMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WPHIqLl7VbrdBDk5w7cFy8nNgl0MDbHUNVVd7MI3I_Q)
> 
> 
> 
> 你这编码有问题吧，搞成代码格式 看看

改了后，就不是显示6060了，显示是5335了

**Comment by Jejz168** [comment]
https://github.com/rufengsuixing/luci-app-adguardhome/issues/148

**Comment by Jejz168** [comment]
local port = luci.sys.exec("awk '/^\\s*dns:/ {found_dns=1} found_dns && /^\\s*port:/ {print $2; exit}' "..configpath.." 2>/dev/null")
/
![捕989获](https://github.com/user-attachments/assets/5dd9af52-6be7-4b15-b4e0-0befcfb72c61)

**Comment by ghost** [comment]
`local port = luci.sys.exec("awk '/^\\s*dns:/ {found_dns=1} found_dns && /^\\s*port:/ {print $2; exit}' "..configpath.." 2>/dev/null")`
![捕989获](https://github.com/user-attachments/assets/a2989bd6-f59a-4d7f-a7c3-885187cf4574)

**Comment by xiangfeidexiaohuo** [comment]
> local port = luci.sys.exec("awk '/^\\s*dns:/ {found_dns=1} found_dns && /^\\s*port:/ {print $2; exit}' "..configpath.." 2>/dev/null")

ok  感谢
